import type { CategoryDTO } from '@core';

/**
 * Category permissions
 */
export interface CategoryPermissions {
  canCreate: boolean;
  canEdit: boolean;
  canDelete: boolean;
}

/**
 * Category form data (UI layer)
 */
export interface CategoryFormData {
  name: string;
  description: string;
}

/**
 * Create category DTO (for POST request body)
 * ID is generated by server
 */
export type CreateCategoryDto = Omit<CategoryDTO, 'id'>;

/**
 * Update category DTO (for PUT request body)
 * ID is passed in URL, body contains only fields to update
 */
export type UpdateCategoryDto = Partial<Omit<CategoryDTO, 'id'>>;
